"""Terraform remediation generator.

For every auto-remediable finding we emit a reviewable Terraform module —
the client-facing artifact that goes into their repository. Modern
`import` blocks (Terraform >= 1.5) bring existing resources under
management, so `terraform plan` shows the exact diff (gp2 -> gp3, lifecycle
rules) and `terraform apply` performs the remediation through standard AWS
APIs. Modules are written to engine/output/terraform/<stamp>/.

In the default demo flow the executor also applies changes directly via
boto3 (deterministic on emulators); the generated modules remain the
reviewable, version-controlled record of what changed.
"""
from __future__ import annotations

import datetime as dt
from pathlib import Path

from . import config


def _provider_block() -> str:
    return '''terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Generated by CloudTrim — apply against the audited account.
# Demo (emulator): defaults work as-is.
# Real AWS: set TF_VAR_aws_access_key / TF_VAR_aws_secret_key, or remove
# the access_key/secret_key attributes to use your standard chain.
variable "aws_access_key" {
  type    = string
  default = "test"
}

variable "aws_secret_key" {
  type    = string
  default = "test"
}

variable "aws_endpoint" {
  type    = string
  default = ""
}

variable "aws_region" {
  type    = string
  default = "%s"
}

provider "aws" {
  region                      = var.aws_region
  access_key                  = var.aws_access_key
  secret_key                  = var.aws_secret_key
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  dynamic "endpoints" {
    for_each = var.aws_endpoint == "" ? [] : [1]
    content {
      ec2        = var.aws_endpoint
      s3         = var.aws_endpoint
      cloudwatch = var.aws_endpoint
    }
  }
}
''' % config.AWS_REGION


def generate_gp3_module(volumes: list[dict]) -> str:
    """Import blocks + desired gp3 state for a batch of volumes."""
    imports = "\n\n".join(
        f"import {{\n  to = aws_ebs_volume.cloudtrim_gp3[{i}]\n  id = \"{v['volume_id']}\"\n}}"
        for i, v in enumerate(volumes))
    az_list = ", ".join(f'"{v["az"]}"' for v in volumes)
    size_list = ", ".join(str(v["size_gb"]) for v in volumes)
    total = sum(v["savings"] for v in volumes)
    resource = f'''
resource "aws_ebs_volume" "cloudtrim_gp3" {{
  count             = {len(volumes)}
  availability_zone = var.az_list[count.index]
  size              = var.size_list[count.index]
  type              = "gp3"   # was gp2 — 20% cheaper per GB-month
  tags = {{
    Name        = "cloudtrim-converted-${{count.index}}"
    managed_by  = "cloudtrim"
  }}
}}

variable "az_list" {{
  type    = list(string)
  default = [{az_list}]
}}

variable "size_list" {{
  type    = list(number)
  default = [{size_list}]
}}
'''
    return f'''
# ---------------------------------------------------------------------------
# EBS gp2 -> gp3 live conversion (zero downtime, modify_volume in-place)
# Saves ${total:,.2f}/mo across {len(volumes)} volumes
# ---------------------------------------------------------------------------

{imports}
{resource}
'''


def generate_s3_lifecycle_module(buckets: list[dict]) -> str:
    rules = []
    for i, b in enumerate(buckets):
        rules.append(f'''
resource "aws_s3_bucket_lifecycle_configuration" "cloudtrim_{i}" {{
  bucket = "{b['bucket']}"

  rule {{
    id     = "cloudtrim-coldening"
    status = "Enabled"

    transition {{
      days          = 30
      storage_class = "STANDARD_IA"
    }}
    transition {{
      days          = 90
      storage_class = "GLACIER_IR"
    }}
    abort_incomplete_multipart_upload {{
      days_after_initiation = 7
    }}
  }}
}}
''')
    header = f'''
# ---------------------------------------------------------------------------
# S3 lifecycle policies (non-disruptive; objects transition in place)
# Saves ${sum(b['savings'] for b in buckets):,.2f}/mo blended on cold data
# ---------------------------------------------------------------------------
'''
    return header + "\n".join(rules)


def write_modules(gp3_volumes: list[dict], lifecycle_buckets: list[dict]) -> Path:
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    out_dir = config.TF_REMEDIATION_DIR / f"{stamp}-remediation"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "provider.tf").write_text(_provider_block())
    if gp3_volumes:
        (out_dir / "ebs_gp3.tf").write_text(generate_gp3_module(gp3_volumes))
    if lifecycle_buckets:
        (out_dir / "s3_lifecycle.tf").write_text(generate_s3_lifecycle_module(lifecycle_buckets))
    (out_dir / "README.md").write_text(
        "# CloudTrim generated remediation modules\n\n"
        "Review the diffs, commit to the audited account's repository, apply via CI.\n"
        "Modules use Terraform 1.5+ `import` blocks to adopt existing resources.\n\n"
        "- `provider.tf` — provider wiring (endpoint overrides for demo emulators;\n"
        "  remove to run against real AWS from your CI)\n"
        "- `ebs_gp3.tf` — gp2 -> gp3 live volume conversions via import blocks\n"
        "- `s3_lifecycle.tf` — S3 lifecycle coldening policies\n")
    return out_dir
